In [64]:
import numpy as np 
import pandas as pd

Write a NumPy program to create an array of all even integers from 30 to 70

In [65]:
## Create an array of all integers from 30 to 70 using np.arange()
x=np.arange(30,70,2)
#np.arange(30, 71, 2) creates an array of integers starting from 30 up to 70 (exclusive) with a step of 2, ensuring that only even integers are included.
print("\nArray of all even integers from 30 to 70:",x)



Array of all even integers from 30 to 70: [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68]


Write a NumPy program to generate an array of 15 random numbers from a standard normal
distribution.

In [66]:
#np.random.randn() is a NumPy function call that generates an array of random numbers from a standard normal distribution.
random_numbers = np.random.randn(15)
#np.random: This is NumPy's submodule for generating random numbers.
#randn: This is a specific function within the np.random submodule that generates random numbers from a normal (Gaussian) distribution with mean 0 and standard deviation 1.

print("Array of 15 random numbers from a standard normal distribution:")
print(random_numbers)


Array of 15 random numbers from a standard normal distribution:
[-0.09790191  0.07131434  1.4450476  -0.21249158 -1.32653052 -0.16602895
  0.97431251  1.13225543  0.92791218 -0.39332269  0.36294108  0.28122824
  0.40208937 -0.49366869 -0.19671776]


How to compute the cross-product of two matrices in NumPy?

In [67]:
import numpy as np

# Define two matrices
matrix_A = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix_B = np.array([[9, 8, 7],
                    [6, 5, 4],
                    [3, 2, 1]])

# Compute the cross product element-wise along axis 1
result_matrix = np.cross(matrix_A, matrix_B, axisa=1, axisb=1)

print("Matrix A:")
print(matrix_A)
print("\nMatrix B:")
print(matrix_B)
print("\nCross Product Matrix:")
print(result_matrix)


Matrix A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
[[9 8 7]
 [6 5 4]
 [3 2 1]]

Cross Product Matrix:
[[-10  20 -10]
 [-10  20 -10]
 [-10  20 -10]]


How to compute the determinant of an array using NumPy?


In [91]:
# we can find the determinent of an array or matrix using numpy with help of determinent function from the linear algebra module. for 
#numpy.linalg.det(a)
a=np.array([[1,2],[3,4]])
print(a)
print("\nDeterminent:")
np.linalg.det(a)



[[1 2]
 [3 4]]

Determinent:


-2.0000000000000004

How to create a 3x3x3 array with random values using NumPy?


In [ ]:
#This will create a 3x3x3 array filled with random values between 0 and 1. 
y=np.random.random((3,3,3))
print(y)
#if we want to genrate random integers we also give them size
x=np.random.randint(0,20,size=(3,3,3))
print(x)

[[[0.4087753  0.65921872 0.23892331]
  [0.92075033 0.69692385 0.30104195]
  [0.399832   0.41282186 0.79669173]]

 [[0.46510833 0.80604158 0.19460805]
  [0.11154422 0.43259292 0.00245272]
  [0.76202658 0.17417459 0.73936029]]

 [[0.00958826 0.55324843 0.36428675]
  [0.62935892 0.73736813 0.60037941]
  [0.67934377 0.15181827 0.9535069 ]]]
[[[ 4  7  7]
  [12  9 12]
  [15 19 12]]

 [[ 1 19  7]
  [ 5  8 19]
  [ 2  9  4]]

 [[15  3  7]
  [19  5 13]
  [ 9 11  3]]]


In [ ]:
# Create a 5x5 array with random values
arr_5x5=np.random.rand(5,5)
print("Array:")
print(arr_5x5)
# Find the minimum and maximum values in the array
arr_5x5.max()
arr_5x5.min()

Array:=
[[0.44075208 0.98323512 0.03315269 0.9975409  0.59273351]
 [0.81218906 0.94612702 0.88475602 0.64023046 0.8720705 ]
 [0.83960197 0.30642327 0.13922431 0.20901449 0.56689168]
 [0.34378182 0.72588575 0.25956017 0.70832352 0.34679533]
 [0.86787775 0.15499276 0.97285065 0.02289568 0.25682244]]


0.022895679927803392

How to compute the mean, standard deviation, and variance of a given array along the second axis in
NumPy?

In [ ]:
# Create a simple array
Array=np.array([[1,2,3],[4,5,6]])
print("\nArray:",Array)
# Calculating mean of given array using np.mean() function along with 2nd axis
mean=np.mean(Array,axis=1)
print("\nMean along the second axis:",mean)


Array: [[1 2 3]
 [4 5 6]]

Mean along the second axis: [2. 5.]


In [ ]:
#Compute the standard deviation along the second axis using np.std()Function
std_dev = np.std(Array, axis=1)
print("Std_dev:",std_dev)

Std_dev: [0.81649658 0.81649658]


In [ ]:
#Compute variance  along the second axis using np.std()Function
variance = np.var(Array, axis=1)
print("variance:",variance)

variance: [0.66666667 0.66666667]
